import type { FailedStartup, DeathCategory } from '@/lib/types'
import { failedStartupsExtraZh } from './seed-data-zh-extra'

export { failedStartupsEn } from './seed-data-en'
export {
  deathCategoryStatsEn,
  deathCategoryStatsZh,
  industryPatternsEn,
  industryPatternsZh,
} from './seed-data-i18n'

export const failedStartups: FailedStartup[] = [
  {
    id: '1',
    name: 'Theranos',
    description: '血检技术公司，声称能用一滴血做数百种检测。硅谷最大创业骗局之一。',
    industry: 'Healthcare',
    cause_of_death: '核心技术造假，产品从未真正工作过',
    death_category: 'product_problems',
    money_raised: 900000000,
    money_burned: 900000000,
    founded_year: 2003,
    died_year: 2018,
    country: 'USA',
    founder_count: 2,
    employee_count: 800,
    lessons_learned: [
      '如果核心技术不work，再多钱也救不了你',
      '不要用NDA和秘密掩盖产品问题',
      '医疗健康领域必须经过严格的科学性验证',
    ],
    market_potential_score: 8,
    rebuild_difficulty: 9,
    tags: ['healthtech', 'fraud', 'hype-over-substance'],
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'WeWork',
    description: '共享办公空间，曾估值470亿美元，IPO前崩塌。',
    industry: 'Real Estate',
    cause_of_death: '单位经济模型崩塌+创始人治理问题',
    death_category: 'unit_economics',
    money_raised: 22000000000,
    money_burned: 12000000000,
    founded_year: 2010,
    died_year: 2023,
    country: 'USA',
    founder_count: 3,
    employee_count: 15000,
    lessons_learned: [
      '用科技公司的估值模型套房地产不可行',
      '长期租约vs短期会员的错配是致命的',
      '创始人治理结构非常重要',
    ],
    market_potential_score: 6,
    rebuild_difficulty: 7,
    tags: ['real-estate', 'coworking', 'governance'],
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Quibi',
    description: '短视频流媒体平台，主打手机端短剧，融资17.5亿美元。',
    industry: 'Media & Entertainment',
    cause_of_death: '没有市场需求——用户不需要一个付费的短视频平台',
    death_category: 'no_market_need',
    money_raised: 1750000000,
    money_burned: 1750000000,
    founded_year: 2018,
    died_year: 2020,
    country: 'USA',
    founder_count: 2,
    employee_count: 250,
    lessons_learned: [
      '名气和资金不能让用户为不需要的东西买单',
      'TikTok和YouTube已经满足短视频需求',
      '在已有免费替代品时，差异化必须极其清晰',
    ],
    market_potential_score: 4,
    rebuild_difficulty: 5,
    tags: ['streaming', 'content', 'tiktok-competitor'],
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'OFO 小黄车',
    description: '中国共享单车鼻祖，曾是最火独角兽。',
    industry: 'Transportation',
    cause_of_death: '盲目扩张+运营失控，车子维护跟不上，变成城市垃圾',
    death_category: 'operations',
    money_raised: 2200000000,
    money_burned: 2200000000,
    founded_year: 2014,
    died_year: 2019,
    country: 'China',
    founder_count: 5,
    employee_count: 3000,
    lessons_learned: [
      '线下运营重资产的复杂度远超想象',
      '烧钱换规模不可持续——单个用户贡献不了利润',
      '竞争导致投放竞赛，全行业一起死',
    ],
    market_potential_score: 7,
    rebuild_difficulty: 6,
    tags: ['sharing-economy', 'bike-sharing', 'china'],
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Better Place',
    description: '电动车换电模式先驱，想做汽车界的苹果。',
    industry: 'Automotive / Energy',
    cause_of_death: '基础设施成本过高，市场时机不对',
    death_category: 'run_out_of_cash',
    money_raised: 850000000,
    money_burned: 850000000,
    founded_year: 2007,
    died_year: 2013,
    country: 'Israel',
    founder_count: 1,
    employee_count: 400,
    lessons_learned: [
      '生不逢时——电动车市场当时太小',
      '换电站建设成本太高，一台换电站要50万美元',
      '标准化依赖整车厂合作，但车厂不愿意',
    ],
    market_potential_score: 9,
    rebuild_difficulty: 7,
    tags: ['ev', 'battery-swap', 'infrastructure', 'too-early'],
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'LeEco 乐视',
    description: '从视频网站扩展到手机、电视、汽车，生态化反。',
    industry: 'Technology / Conglomerate',
    cause_of_death: '过度扩张+现金流断裂，资金链断裂引发连锁反应',
    death_category: 'run_out_of_cash',
    money_raised: 12000000000,
    money_burned: 12000000000,
    founded_year: 2004,
    died_year: 2017,
    country: 'China',
    founder_count: 1,
    employee_count: 14000,
    lessons_learned: [
      '多元化扩张必须在主营业务盈利之后',
      '资金链管理是创业者的第一要务',
      'PPT造车不能替代真正的产品研发',
    ],
    market_potential_score: 5,
    rebuild_difficulty: 8,
    tags: ['conglomerate', 'china', 'over-expansion', 'cash-flow'],
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Essential Products',
    description: 'Android之父Andy Rubin创办的手机公司。',
    industry: 'Consumer Hardware',
    cause_of_death: '产品差异化不足+竞争激烈，无法与苹果三星竞争',
    death_category: 'competition',
    money_raised: 330000000,
    money_burned: 300000000,
    founded_year: 2015,
    died_year: 2020,
    country: 'USA',
    founder_count: 1,
    employee_count: 150,
    lessons_learned: [
      '名人创始人不是护城河',
      '消费电子市场巨头垄断严重',
      '一款好手机不等于一家好公司',
    ],
    market_potential_score: 3,
    rebuild_difficulty: 8,
    tags: ['hardware', 'smartphone', 'competition'],
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: '柔宇科技 Royole',
    description: '折叠屏技术先驱，全球首款折叠屏手机。',
    industry: 'Consumer Hardware / Displays',
    cause_of_death: '产品技术问题+资金链断裂，无法量产',
    death_category: 'product_problems',
    money_raised: 2600000000,
    money_burned: 2600000000,
    founded_year: 2012,
    died_year: 2024,
    country: 'China',
    founder_count: 2,
    employee_count: 2000,
    lessons_learned: [
      '实验室技术≠可量产产品',
      '硬件创业的资金消耗远超软件',
      '先发优势抵不过供应链劣势',
    ],
    market_potential_score: 8,
    rebuild_difficulty: 9,
    tags: ['hardware', 'foldable-display', 'manufacturing', 'china'],
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Fast (Checkout)',
    description: '一键结账SaaS，对标 Bolt 和 Shopify。',
    industry: 'E-commerce / SaaS',
    cause_of_death: '烧钱过快+收入几乎为零，商业模式未经验证就疯狂扩张',
    death_category: 'unit_economics',
    money_raised: 124000000,
    money_burned: 120000000,
    founded_year: 2019,
    died_year: 2022,
    country: 'USA',
    founder_count: 2,
    employee_count: 400,
    lessons_learned: [
      '收入没跑通之前，不要雇400人',
      'SaaS的销售周期比你想象的长',
      '竞品Bolt和Shopify已经有生态优势',
    ],
    market_potential_score: 5,
    rebuild_difficulty: 4,
    tags: ['saas', 'e-commerce', 'checkout', 'fast-growth'],
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'MoviePass',
    description: '电影订阅服务，月费$10无限看。',
    industry: 'Entertainment',
    cause_of_death: '单位经济崩塌——每卖一个会员亏更多钱',
    death_category: 'unit_economics',
    money_raised: 200000000,
    money_burned: 200000000,
    founded_year: 2011,
    died_year: 2020,
    country: 'USA',
    founder_count: 2,
    employee_count: 100,
    lessons_learned: [
      '补贴用户必须有一个清晰的盈利路径',
      '定价必须在覆盖成本的基础上',
      '电影院的票价不是你能控制的',
    ],
    market_potential_score: 6,
    rebuild_difficulty: 5,
    tags: ['subscription', 'entertainment', 'pricing-failure'],
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Lekee 乐住',
    description: '酒店SaaS管理系统，为中小酒店提供服务。',
    industry: 'Hospitality / SaaS',
    cause_of_death: '中小酒店付费意愿低，养不起销售和研发团队',
    death_category: 'unit_economics',
    money_raised: 42000000,
    money_burned: 42000000,
    founded_year: 2015,
    died_year: 2019,
    country: 'China',
    founder_count: 3,
    employee_count: 500,
    lessons_learned: [
      '中国中小商家的SaaS付费意愿是真实难题',
      '面向小客户的SaaS必须极低成本获客',
      '功能堆砌不等于价值',
    ],
    market_potential_score: 6,
    rebuild_difficulty: 4,
    tags: ['saas', 'hospitality', 'china', 'smb'],
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Beepi',
    description: 'P2P二手车交易平台，想做二手车界的Airbnb。',
    industry: 'Automotive',
    cause_of_death: '运营成本过高，每卖一辆车亏损数万美元',
    death_category: 'operations',
    money_raised: 150000000,
    money_burned: 150000000,
    founded_year: 2013,
    died_year: 2017,
    country: 'USA',
    founder_count: 2,
    employee_count: 300,
    lessons_learned: [
      '二手车检测和翻新的成本远超预期',
      '低频交易撑不起高运营成本',
      '两边的信任问题比想象中更难解决',
    ],
    market_potential_score: 5,
    rebuild_difficulty: 6,
    tags: ['auto', 'p2p', 'marketplace', 'operations-heavy'],
    created_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Jawbone',
    description: '可穿戴设备先驱，比Fitbit更早进入市场。',
    industry: 'Consumer Hardware',
    cause_of_death: '产品品质问题+竞争加剧+资金耗尽',
    death_category: 'product_problems',
    money_raised: 900000000,
    money_burned: 900000000,
    founded_year: 1999,
    died_year: 2017,
    country: 'USA',
    founder_count: 2,
    employee_count: 400,
    lessons_learned: [
      '先发优势不等于成功，品控是关键',
      '硬件迭代成本远高于软件',
      '产品召回对品牌是毁灭性的',
    ],
    market_potential_score: 7,
    rebuild_difficulty: 7,
    tags: ['wearable', 'hardware', 'quality-issues'],
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'Zume Pizza',
    description: '机器人做披萨+配送，软银愿景基金投资。',
    industry: 'Food Tech',
    cause_of_death: '机器人做披萨是伪需求，核心技术不成立',
    death_category: 'product_problems',
    money_raised: 445000000,
    money_burned: 445000000,
    founded_year: 2015,
    died_year: 2023,
    country: 'USA',
    founder_count: 2,
    employee_count: 500,
    lessons_learned: [
      '用自动化解决不存在的问题=烧钱',
      '食品行业的核心是口味，不是机器人',
      '软银投的不一定对',
    ],
    market_potential_score: 3,
    rebuild_difficulty: 8,
    tags: ['food-tech', 'robotics', 'hype', 'softbank'],
    created_at: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'Katerra',
    description: '科技驱动的建筑公司，从设计到施工一体化。',
    industry: 'Construction',
    cause_of_death: '过度扩张+运营混乱+成本失控',
    death_category: 'operations',
    money_raised: 2000000000,
    money_burned: 2000000000,
    founded_year: 2015,
    died_year: 2021,
    country: 'USA',
    founder_count: 3,
    employee_count: 8000,
    lessons_learned: [
      '建筑行业极其复杂，不是加个APP就能颠覆的',
      '通过收购拼凑起来的公司文化是灾难',
      '实体供应链比代码难管太多了',
    ],
    market_potential_score: 7,
    rebuild_difficulty: 8,
    tags: ['construction', 'vertical-integration', 'supply-chain'],
    created_at: new Date().toISOString(),
  },
  {
    id: '16',
    name: 'Infarm',
    description: '垂直农业/室内种植，为超市提供新鲜蔬菜。',
    industry: 'Agriculture / Food Tech',
    cause_of_death: '室内种植成本远超传统农业，单位经济彻底崩塌',
    death_category: 'unit_economics',
    money_raised: 600000000,
    money_burned: 600000000,
    founded_year: 2013,
    died_year: 2023,
    country: 'Germany',
    founder_count: 3,
    employee_count: 1000,
    lessons_learned: [
      '环保理念不能替代经济可行性',
      '与传统农业比成本是几乎不可能赢的',
      '超市的利润空间容不下高成本的本地种植',
    ],
    market_potential_score: 8,
    rebuild_difficulty: 7,
    tags: ['agtech', 'vertical-farming', 'climate', 'germany'],
    created_at: new Date().toISOString(),
  },
  {
    id: '17',
    name: 'Arrivo',
    description: 'Hyperloop（超级高铁）创业公司。',
    industry: 'Transportation',
    cause_of_death: '技术难度远超想象，资金需求天文数字',
    death_category: 'tech_failure',
    money_raised: 1000000000,
    money_burned: 1000000000,
    founded_year: 2016,
    died_year: 2018,
    country: 'USA',
    founder_count: 1,
    employee_count: 50,
    lessons_learned: [
      '科幻级技术不适合创业公司',
      '基础设施项目的资金需求超出VC能力范围',
      '监管审批的时间成本往往被严重低估',
    ],
    market_potential_score: 5,
    rebuild_difficulty: 10,
    tags: ['hyperloop', 'infrastructure', 'moonshot'],
    created_at: new Date().toISOString(),
  },
  {
    id: '18',
    name: 'GOGOKID',
    description: '字节跳动旗下在线英语教育平台。',
    industry: 'EdTech',
    cause_of_death: '中国"双减"政策冲击+获客成本极高',
    death_category: 'regulatory',
    money_raised: 500000000,
    money_burned: 500000000,
    founded_year: 2017,
    died_year: 2021,
    country: 'China',
    founder_count: 0,
    employee_count: 2000,
    lessons_learned: [
      '教育行业受政策影响极大',
      '依赖广告获客的教育SaaS商业模式脆弱',
      '大厂内部创业不等于不会失败',
    ],
    market_potential_score: 7,
    rebuild_difficulty: 6,
    tags: ['edtech', 'china', 'regulation', 'tutoring'],
    created_at: new Date().toISOString(),
  },
  {
    id: '19',
    name: '99dresses',
    description: '二手女装租赁交易平台。',
    industry: 'E-commerce / Fashion',
    cause_of_death: '运营成本过高，人工审核需求巨大，AI不成熟时纯靠人力',
    death_category: 'operations',
    money_raised: 1000000,
    money_burned: 1000000,
    founded_year: 2011,
    died_year: 2014,
    country: 'Australia',
    founder_count: 1,
    employee_count: 10,
    lessons_learned: [
      '二手服装的质检和分类成本极高',
      '在AI成熟之前，非标品交易平台很难以低成本运营',
      '女性时尚市场的复购率和用户黏性被高估',
    ],
    market_potential_score: 7,
    rebuild_difficulty: 3,
    tags: ['fashion', 'second-hand', 'marketplace', 'women-founders'],
    created_at: new Date().toISOString(),
  },
  {
    id: '20',
    name: 'Sidecar',
    description: '比Uber更早的共享出行平台，发明了P2P拼车模式。',
    industry: 'Transportation',
    cause_of_death: '被Uber和Lyft在市场份额和资金上碾压',
    death_category: 'competition',
    money_raised: 35000000,
    money_burned: 35000000,
    founded_year: 2011,
    died_year: 2015,
    country: 'USA',
    founder_count: 2,
    employee_count: 100,
    lessons_learned: [
      '先发优势在绝对的资金优势面前不算什么',
      '网络效应市场只会剩1-2家',
      '在巨头融资数十亿的赛道里，融不到钱就是等死',
    ],
    market_potential_score: 6,
    rebuild_difficulty: 7,
    tags: ['ride-sharing', 'uber-competitor', 'network-effects'],
    created_at: new Date().toISOString(),
  },
  {
    id: '21',
    name: 'Rdio',
    description: '音乐流媒体先驱，设计极佳但败给了Spotify。',
    industry: 'Music / Streaming',
    cause_of_death: '用户增长太慢+版权成本过高，被Spotify彻底超越',
    death_category: 'competition',
    money_raised: 120000000,
    money_burned: 120000000,
    founded_year: 2010,
    died_year: 2015,
    country: 'USA',
    founder_count: 2,
    employee_count: 200,
    lessons_learned: [
      '好设计不能替代增长策略',
      '内容版权获取能力决定了流媒体生死',
      '免费增值模式需要极大的资金支持',
    ],
    market_potential_score: 5,
    rebuild_difficulty: 6,
    tags: ['streaming', 'music', 'spotify-competitor'],
    created_at: new Date().toISOString(),
  },
  {
    id: '22',
    name: 'PepperTap',
    description: '印度生鲜电商，1小时送达。',
    industry: 'E-commerce / Grocery',
    cause_of_death: '运营成本+损耗率超出预期，每单亏损严重',
    death_category: 'unit_economics',
    money_raised: 52000000,
    money_burned: 52000000,
    founded_year: 2014,
    died_year: 2016,
    country: 'India',
    founder_count: 2,
    employee_count: 1500,
    lessons_learned: [
      '生鲜电商的供应链和损耗是最难解决的问题',
      '配送成本在发展中国家难以通过规模降低',
      '用户的比价行为让你永远无法提价',
    ],
    market_potential_score: 7,
    rebuild_difficulty: 8,
    tags: ['grocery', 'india', 'delivery', 'e-commerce'],
    created_at: new Date().toISOString(),
  },
  {
    id: '23',
    name: 'ScaleFactor',
    description: 'AI+人工合一的自动记账/会计SaaS。',
    industry: 'FinTech / SaaS',
    cause_of_death: 'AI做不了真正的会计——大量后端依赖人工，不是真正的SaaS',
    death_category: 'product_problems',
    money_raised: 100000000,
    money_burned: 100000000,
    founded_year: 2014,
    died_year: 2020,
    country: 'USA',
    founder_count: 1,
    employee_count: 200,
    lessons_learned: [
      '假AI(AI-washing)终将被拆穿',
      '声称是SaaS但后台用人工是不可持续的',
      '企业会计的复杂度远超创业者的想象',
    ],
    market_potential_score: 8,
    rebuild_difficulty: 5,
    tags: ['fintech', 'accounting', 'ai-washing', 'saas'],
    created_at: new Date().toISOString(),
  },
  {
    id: '24',
    name: 'Bodega',
    description: '无人零售柜，放在公寓楼大厅卖日用品。',
    industry: 'Retail / Vending',
    cause_of_death: '商业模式不成立+品牌公关灾难+文化冒犯指控',
    death_category: 'no_market_need',
    money_raised: 2500000,
    money_burned: 2500000,
    founded_year: 2016,
    died_year: 2020,
    country: 'USA',
    founder_count: 2,
    employee_count: 20,
    lessons_learned: [
      '便利店/小卖部的核心竞争力是人情味和便利性',
      '品牌命名和文化敏感性极度重要',
      '无人零售的技术成本在2016年过高',
    ],
    market_potential_score: 5,
    rebuild_difficulty: 5,
    tags: ['retail', 'vending', 'branding-fail'],
    created_at: new Date().toISOString(),
  },
  {
    id: '25',
    name: 'Powa Technologies',
    description: '英国支付和电商技术公司。',
    industry: 'FinTech',
    cause_of_death: '收入造假+过度吹嘘+真正产品不如PPT描述',
    death_category: 'product_problems',
    money_raised: 225000000,
    money_burned: 225000000,
    founded_year: 2007,
    died_year: 2016,
    country: 'UK',
    founder_count: 1,
    employee_count: 300,
    lessons_learned: [
      '财务造假终将暴露',
      '英国科技创业需要更严格的尽调',
      'sales-first产品-last的文化是毒药',
    ],
    market_potential_score: 4,
    rebuild_difficulty: 4,
    tags: ['fintech', 'uk', 'fraud', 'payments'],
    created_at: new Date().toISOString(),
  },
  {
    id: '26',
    name: 'Homejoy',
    description: '按需家政服务O2O平台。',
    industry: 'Home Services',
    cause_of_death: '清洁工分类为员工vs承包商的诉讼+留存率极低',
    death_category: 'legal_issues',
    money_raised: 40000000,
    money_burned: 40000000,
    founded_year: 2012,
    died_year: 2015,
    country: 'USA',
    founder_count: 2,
    employee_count: 150,
    lessons_learned: [
      'O2O平台的法律风险(1099 vs W2)是致命的',
      '低频服务的复购率撑不起VC级别的增长',
      '高频补贴拉来的用户，停止补贴就走',
    ],
    market_potential_score: 5,
    rebuild_difficulty: 6,
    tags: ['home-services', 'o2o', 'legal', '1099'],
    created_at: new Date().toISOString(),
  },
  {
    id: '27',
    name: 'Maple',
    description: '纽约按需送餐服务。',
    industry: 'Food Delivery',
    cause_of_death: '自己做饭+配送的模式单位经济太差',
    death_category: 'unit_economics',
    money_raised: 29000000,
    money_burned: 29000000,
    founded_year: 2014,
    died_year: 2017,
    country: 'USA',
    founder_count: 2,
    employee_count: 100,
    lessons_learned: [
      '自营+配送=双重成本',
      '只做一个城市无法摊销中央厨房成本',
      '食客对价格极度敏感',
    ],
    market_potential_score: 4,
    rebuild_difficulty: 5,
    tags: ['food-delivery', 'new-york', 'dark-kitchen'],
    created_at: new Date().toISOString(),
  },
  {
    id: '28',
    name: 'Yik Yak',
    description: '匿名校园社交应用，曾是校园爆款。',
    industry: 'Social Media',
    cause_of_death: '匿名导致的网络霸凌+内容审核成本+用户流失',
    death_category: 'operations',
    money_raised: 73000000,
    money_burned: 73000000,
    founded_year: 2013,
    died_year: 2017,
    country: 'USA',
    founder_count: 2,
    employee_count: 50,
    lessons_learned: [
      '匿名社交的内容审核成本呈指数级增长',
      '校园社交的时间窗口极短——学生4年毕业',
      '负面新闻(欺凌)会让品牌彻底死亡',
    ],
    market_potential_score: 3,
    rebuild_difficulty: 4,
    tags: ['social-media', 'anonymous', 'content-moderation'],
    created_at: new Date().toISOString(),
  },
  {
    id: '29',
    name: 'Color Genomics',
    description: '基因检测消费者化，从癌症筛查转向群体健康。',
    industry: 'Healthcare / Genomics',
    cause_of_death: '消费者基因检测市场远小于预期+23andMe先发碾压',
    death_category: 'no_market_need',
    money_raised: 150000000,
    money_burned: 100000000,
    founded_year: 2013,
    died_year: 2021,
    country: 'USA',
    founder_count: 2,
    employee_count: 100,
    lessons_learned: [
      '消费者健康市场远不如B2B健康市场大',
      '基因检测的复购率几乎为零',
      '医疗产品必须走保险/企业付费路线',
    ],
    market_potential_score: 6,
    rebuild_difficulty: 5,
    tags: ['genomics', 'healthcare', 'consumer-health', 'pivot'],
    created_at: new Date().toISOString(),
  },
  {
    id: '30',
    name: 'Airsense',
    description: 'AI气味分析/数字嗅觉传感器。',
    industry: 'Hardware / AI',
    cause_of_death: '技术可行但使用场景过于模糊，没有明确购买动因',
    death_category: 'no_market_need',
    money_raised: 15000000,
    money_burned: 15000000,
    founded_year: 2016,
    died_year: 2022,
    country: 'UK',
    founder_count: 2,
    employee_count: 50,
    lessons_learned: [
      '酷炫技术≠有市场',
      '工业B2B可能是更好的方向但需要更长的销售周期',
      '硬件的迭代周期和资金需求需要准确估算',
    ],
    market_potential_score: 6,
    rebuild_difficulty: 7,
    tags: ['ai', 'hardware', 'sensors', 'deep-tech'],
    created_at: new Date().toISOString(),
  },
]

// Combined Chinese dataset: 30 curated translations + 70 from loot-drop
export const failedStartupsZh: FailedStartup[] = [...failedStartups, ...failedStartupsExtraZh]

export const deathCategoryStats: Record<DeathCategory, { lethality: number; description: string }> = {
  product_problems: { lethality: 85.6, description: 'Bug多、体验差、质量低劣、没解决真实问题' },
  competition: { lethality: 82.7, description: '被对手干掉、无法差异化、市场太拥挤' },
  unit_economics: { lethality: 62.6, description: '卖一单亏一单、CAC > LTV、利润率为负' },
  operations: { lethality: 54.2, description: '无法规模化、物流崩溃、供应链断裂' },
  run_out_of_cash: { lethality: 53.1, description: '烧光资金、无法继续融资' },
  team_issues: { lethality: 48.7, description: '创始人内讧、关键人才缺失、招错人' },
  no_market_need: { lethality: 36.2, description: '解决一个没人有的问题、时机不对、市场太小' },
  regulatory: { lethality: 31.5, description: '政策变化、监管突然收紧' },
  pivot_gone_wrong: { lethality: 22.8, description: '转型转进坑里、失去原有优势' },
  tech_failure: { lethality: 18.4, description: '核心技术不work、无法规模化' },
  legal_issues: { lethality: 14.3, description: '诉讼、知识产权纠纷、合规问题' },
}

// Industry-specific failure patterns
export const industryPatterns: Record<string, string[]> = {
  'E-commerce': ['83% 死于竞争', '70% 死于运营问题', '物流和退货成本是最大隐性杀手'],
  'Healthcare': ['94% 死于监管红线', 'B2B 模式远优于 B2C', '医疗决策者≠付费者≠使用者'],
  'Hardware': ['96% 死于产品问题', '76% 烧光现金', '硬件创业资金需求是软件的 10 倍以上'],
  'SaaS': ['高竞争（低门槛）', '获客成本是关键', '留存率低于 90% 不可能盈利'],
  'FinTech': ['监管是最大风险', '合规成本容易被低估', '用户信任建立周期极长'],
  'EdTech': ['政策风险极高', '学校/机构的销售周期极长（6-18 个月）', 'B2C 获客成本远超预期'],
  'Food & Beverage': ['毛利率低（通常 5-15%）', '供应链管理是核心竞争力', '食品安全事故可瞬间杀死公司'],
  'Social Media': ['网络效应门槛极高', '内容审核成本呈指数增长', '用户口味变化极快'],
  'Marketplace': ['先有鸡还是先有蛋的冷启动问题', '供需双方的信任建立', '流动性是最重要指标'],
}
