"use client"

import { useLang } from "@/lib/i18n/language-context"

const content = {
  en: {
    title: "Terms of Service",
    lastUpdated: "Last updated: May 25, 2026",
    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: "By using Graveyard Gold (\"the Service\"), you agree to these Terms of Service. If you do not agree, do not use the Service.",
      },
      {
        heading: "2. Description of Service",
        body: "Graveyard Gold is an AI-powered startup idea validation tool. You submit a startup idea, and the Service generates a risk analysis report based on historical startup failure data. The Service is provided for educational and informational purposes only.",
      },
      {
        heading: "3. No Professional Advice",
        body: "The analysis reports generated by the Service are AI-generated content based on historical data patterns. They do not constitute professional business, legal, financial, or investment advice. You should consult qualified professionals before making business decisions based on the reports.",
      },
      {
        heading: "4. User Content",
        body: "You retain all rights to the startup ideas you submit. By submitting an idea, you grant us a limited license to process it for the purpose of generating your analysis report. We do not claim ownership of your ideas and will not use them to compete with you.",
      },
      {
        heading: "5. AI-Generated Content",
        body: "The Service uses artificial intelligence to generate reports. AI-generated content may contain errors, inaccuracies, or \"hallucinations.\" We do not guarantee the accuracy, completeness, or usefulness of any analysis report. Use the reports at your own risk.",
      },
      {
        heading: "6. Limitation of Liability",
        body: "The Service is provided \"as is\" without warranties of any kind. We shall not be liable for any damages arising from the use of the Service, including but not limited to business losses, lost profits, or decisions made based on analysis reports.",
      },
      {
        heading: "7. Fair Use",
        body: "You agree not to:\n• Submit automated or bulk requests\n• Use the Service for illegal purposes\n• Attempt to reverse-engineer the Service\n• Submit content that violates others' intellectual property rights\nWe reserve the right to block access for violations of fair use.",
      },
      {
        heading: "8. Changes to Terms",
        body: "We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.",
      },
      {
        heading: "9. Contact",
        body: "For questions about these terms, contact us at legal@graveyardgold.com.",
      },
    ],
  },
  zh: {
    title: "服务条款",
    lastUpdated: "最后更新：2026 年 5 月 25 日",
    sections: [
      {
        heading: "1. 接受条款",
        body: "使用 Graveyard Gold（「本服务」）即表示您同意本服务条款。如果您不同意，请勿使用本服务。",
      },
      {
        heading: "2. 服务描述",
        body: "Graveyard Gold 是一个 AI 驱动的创业想法验证工具。您提交创业想法，本服务基于历史创业失败数据生成风险分析报告。本服务仅供教育和信息参考目的。",
      },
      {
        heading: "3. 非专业建议",
        body: "本服务生成的分析报告是基于历史数据模式的 AI 生成内容，不构成专业的商业、法律、财务或投资建议。在根据报告做出商业决策之前，您应咨询合格的专业人士。",
      },
      {
        heading: "4. 用户内容",
        body: "您保留对所提交的创业想法的一切权利。提交想法即表示您授予我们有限的许可，以处理该想法并生成分析报告。我们不主张对您的想法拥有所有权，也不会利用您的想法与您竞争。",
      },
      {
        heading: "5. AI 生成内容",
        body: "本服务使用人工智能生成报告。AI 生成的内容可能包含错误、不准确或「幻觉」。我们不保证任何分析报告的准确性、完整性或实用性。使用报告的风险由您自行承担。",
      },
      {
        heading: "6. 责任限制",
        body: "本服务按「原样」提供，不作任何形式的保证。对于因使用本服务而产生的任何损害，包括但不限于商业损失、利润损失或基于分析报告做出的决策，我们不承担任何责任。",
      },
      {
        heading: "7. 合理使用",
        body: "您同意不：\n• 提交自动化或批量请求\n• 将本服务用于非法目的\n• 试图逆向工程本服务\n• 提交侵犯他人知识产权的内容\n我们保留对违反合理使用的行为进行封禁的权利。",
      },
      {
        heading: "8. 条款变更",
        body: "我们保留随时修改这些条款的权利。在变更后继续使用本服务即表示接受新条款。",
      },
      {
        heading: "9. 联系方式",
        body: "有关这些条款的问题，请通过 legal@graveyardgold.com 与我们联系。",
      },
    ],
  },
}

export default function TermsPage() {
  let lang = "en" as "en" | "zh"
  try {
    const ctx = useLang()
    lang = ctx.lang
  } catch {
    // useLang may not be available
  }
  const t = content[lang]

  return (
    <main className="flex-1 px-4 py-12 max-w-2xl mx-auto w-full">
      <h1 className="text-3xl font-bold mb-2">{t.title}</h1>
      <p className="text-sm text-neutral-500 mb-8">{t.lastUpdated}</p>
      <div className="space-y-6">
        {t.sections.map((section, i) => (
          <section key={i}>
            <h2 className="text-lg font-semibold mb-2">{section.heading}</h2>
            <p className="text-sm text-neutral-400 whitespace-pre-line leading-relaxed">{section.body}</p>
          </section>
        ))}
      </div>
    </main>
  )
}
